### ISSUE TITLE
Map view should include all current results initially

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#258]
On cases search, when the map view is toggle it should be at a zoom level that includes all of the current search results (and ideally not be zoomed beyond those). This way, toggling back to text view would not result in fewer results being shown (from a narrow bounding box). 

Currently, clicking the map and then going back to text results in a narrow bounding box being applied.

**Comment by inghamn** [comment]
It's confusing having the map automatically filter the results without the user knowing.  We want to make it an explicit action for the user to apply the map (as they see it) as a filter.

If the user does not apply the filter, then switching back to the Text Results should not add the Map Filter to the search results.

- [ ] Set zoom level 12 initially
- [ ] Change wording to "Map Filter" instead of "Bounding Box"
- [ ] The header for the map should also be "Map Filter" instead of "search results"
- [ ] Draw an apply button that applies the map filter.
