### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by slamonega** [City-of-Bloomington/uReport#378]
I can translate the system to spanish, tell me wich files are necesary.

**Comment by slamonega** [comment]
maybe I can use the french translation files as a reference. 

uReport/crm/language/fr_CA/LC_MESSAGES/

This files are enough?

**Comment by inghamn** [comment]
Thanks very much for your interest.  
Yes, the LC_MESSAGES files are the only thing that's needed to provide a translation.  All text in the application comes from LC_MESSAGES.

The application is originally in English, which *might* be a more complete reference.  I've tried to make sure to keep all languages up to date as I add more text, but I cannot be sure that I all the languages are complete.

I'm happy to merge whatever you have time to contribute.  It has been a long time since I've had time to work on this project.  I know the installation instructions are a bit out of date.  I'm happy to answer any questions you have.
